version: '3.8'

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: mel_collecte_local_ha
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components/mel_collecte:ro
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    network_mode: host